[netjammer]
enabled = true
votes_to_skip = 3
max_tracks = 0
max_results = 50
max_queue_length = 0
max_song_duration = 0
default_volume = 30
hide_pause = false
hide_skip = false
style = netjammer.css
source_prio = local
  spotify
  tidal
  youtube
source_blacklist = cd
lastfm_api_key =
radio_min_queue = 2
radio_batch = 5
radio_seed_count = 3
